name: Price Bot - Bale

on:
  schedule:
    # 11 بار در روز از 6 صبح تا 12 شب (UTC)
    - cron: '30 2,4,5,7,8,10,11,13,14,16,17 * * *'
    
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          CHANNEL_LINK: ${{ secrets.CHANNEL_LINK }}
          AD_LINK: ${{ secrets.AD_LINK }}
        run: python bot.py
